# Generated by Django 3.0.3 on 2020-03-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='Task',
        ),
    ]
