# Generated by Django 3.0.3 on 2020-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200301_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='placa',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='servico',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
